version: '3.8'

services:
  telegram-bot-openproject:
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
      - db_data:/app/telegram_app
      - ./logs:/app/logs  # Монтируем директорию для логов с хоста

volumes:
  db_data: